export { default as Page404 } from './404'
export { default as Auth } from './Auth/index'
export { default as Student } from './Student'
export { default as Admin } from './Admin'
// export { default as Home } from './Home'
export { default as Users } from './Users/index'
export { default as Questions } from './Questions/index'
export { default as Profile } from './Profile/index'
export { default as Logout } from './Logout'
export { default as Settings } from './Settings'
export { default as Quizzes } from './Quizzes'
export { default as Appraisal } from './Appraisal'
export { default as Statistics } from './Statistics'
